const ADD_SPRINT = "@SPRINTS/addSPRINT";
const GET_SPRINTS = "@SPRINTS/getSPRINTS";
const SHOW_MODAL_ADD_SPRINT = "@SPRINTS/showModalAddSPRINT";
const DELETE_SPRINT = "@SPRINTS/deleteSPRINT";

export default {
  ADD_SPRINT,
  GET_SPRINTS,
  SHOW_MODAL_ADD_SPRINT,
  DELETE_SPRINT,
};

// const CHANGE_SPRINT = "@SPRINTS/changeSPRINT";
// const FILTER_SPRINTS = "@SPRINTS/filterSPRINTS";
// const DELETE_SPRINT = "@SPRINTS/deleteSPRINT";
